global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "chat-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["chat-service:8000"]

  - job_name: "admin-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["admin-service:8000"]