# Grafana Alerting Provisioning Configuration
# This file configures alerting rules and notification policies

apiVersion: 1

# Contact points for notifications
contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: admin@example.com
        disableResolveMessage: false

# Notification policies
policies:
  - orgId: 1
    receiver: default-email
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h

# Alert rules
rules:
  - orgId: 1
    name: "System Alerts"
    folder: "alerts"
    interval: 1m
    rules: []